### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by havenchyk** [imagemin/imagemin-gifsicle#16]
Following this issue https://github.com/tcoopman/image-webpack-loader/issues/50

it looks like this plugin throws a warning in latest node with image-webpack-loader

```
(node:6562) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at EventEmitter.addListener (events.js:276:10)
    at module.exports (/Users/front/node_modules/signal-exit/index.js:41:11)
    at module.exports (/Users/front/node_modules/execa/index.js:146:23)
    at fsP.writeFile.then (/Users/front/node_modules/exec-buffer/index.js:35:15)
```

it looks like the problem is in execa, https://github.com/sindresorhus/execa/issues/61
so it would be great to update this lib when issue there will be fixed

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin/issues/211#issuecomment-271146283
