### ISSUE TITLE
Error: gifsicle: unrecognized option ‘--no-app-extensions’

### ISSUE THREAD

**Issue by r007** [imagemin/imagemin-gifsicle#29]
Hi there,

This module is throwing an error:

```(node:13118) UnhandledPromiseRejectionWarning: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/home/r007/Projects/startuplywp-wordpress-theme/source/node_modules/execa/index.js:231:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:13118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I have ```gifsicle``` 4.0.1 installed. ```Imagemin``` and ```imagemin-gifsicle``` are the latest ones. Also, people have similar issue with unrecognized option https://github.com/JeffreyWay/laravel-mix/issues/1321#issue-274135321. Everything works fine when I remove --no-app-extensions from index.js.

Can you fix it, please?

**Comment by tomsoderlund** [comment]
I had this exact error with `grunt-contrib-imagemin`, but fixed it by upgrading it (from v2.0.1) to v3.1.0. This upgrade also brought `imagemin-gifsicle-6.0.1` and `gifsicle-4.0.1`.
