### ISSUE TITLE
Postinstall failed : ENOTFOUND

### ISSUE THREAD

**Issue by ThomasCrvsr** [imagemin/imagemin-gifsicle#3]
Hello,

While working with the latest version of `grunt-contrib-imagemin` I saw that there is some problems with the latest versions of some dependencies (`imagemin-gifsicle`, `imagemin-jpegtran` and `imagemin-optipng`) :

```
> gifsicle@3.0.1 postinstall /home/d2i/Documents/test-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Request to https://raw.github.com/imagemin/gifsicle-bin/3.0.1/vendor/linux/x64/gifsicle failed
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ GotError: Request to http://www.lcdf.org/gifsicle/gifsicle-1.87.tar.gz failed
    at ClientRequest.<anonymous> (/home/d2i/Documents/test-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/got/index.js:177:7)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Caused By: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

I guess it comes from the latest updates of the packages `gifsicle-bin`, `jpegtran-bin` and `optipng-bin` (I work on Ubuntu).

**Comment by kevva** [comment]
Are you behind a proxy?

**Comment by ThomasCrvsr** [comment]
Yep

**Comment by kevva** [comment]
See https://github.com/kevva/download/issues/64.
