### ISSUE TITLE
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"

### ISSUE THREAD

**Issue by zzroche** [imagemin/imagemin-gifsicle#33]
When I try to install gifsicle on Windows 10 Pro (with other gulp plugin I don't have any problem):

npm install imagemin-gifsicle --save-dev

> gifsicle@4.0.1 postinstall c:\Users\...\Documents\...\node_modules\gifsicle
> node lib/install.js

  ‼ tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
"autoreconf" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

    at Promise.all.then.arr (c:\Users\...\Documents\...\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN apodoc@1.0.0 No description
npm WARN apodoc@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@4.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@4.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by rapidfixer** [comment]
What's up with this issue?

**Comment by vsanse** [comment]
any solution @zzroche

**Comment by maanishoo** [comment]
Any ideas?

**Comment by vsanse** [comment]
> Any ideas?

Global install with npm seems to fail on windows works fine when installed as dependency

**Comment by mahesheru** [comment]
Any one has fixed this issue, i am seeing the same error in windows .
  x Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,

**Comment by chackop** [comment]
> > Any ideas?
> 
> Global install with npm seems to fail on windows works fine when installed as dependency

@vsanse Which dependency was installed that worked for you?

**Comment by vsanse** [comment]
> > > Any ideas?
> > 
> > 
> > Global install with npm seems to fail on windows works fine when installed as dependency
> 
> @vsanse Which dependency was installed that worked for you?

gifsicle

**Comment by namkee** [comment]
In my case, it was worked around with running 'cmd' as administrator,

**Comment by j78742** [comment]
> In my case, it was worked around with running 'cmd' as administrator,

I have tried your manner, but never works for me

**Comment by Lumersgo** [comment]
In my case, 3 steps  solved this problem.
- set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
- add 199.232.4.133 raw.githubusercontent.com to hosts files.
- cmd.exe  ipconfig/flushdns

**Comment by z970445720** [comment]
You can try to use cnpm of Taobao mirror：
1、npm install -g cnpm --registry=https://registry.npm.taobao.org
2、cnpm i -g gifsicle

**Comment by TLS-Hoare** [comment]
If ping raw.githubusercontent.com timed out
add hosts
```
52.74.223.119     github.com
192.30.253.119    gist.github.com
54.169.195.247    api.github.com
185.199.111.153   assets-cdn.github.com
151.101.76.133    raw.githubusercontent.com
151.101.76.133    gist.githubusercontent.com
151.101.76.133    cloud.githubusercontent.com
151.101.76.133    camo.githubusercontent.com
151.101.76.133    avatars0.githubusercontent.com
151.101.76.133    avatars1.githubusercontent.com
151.101.76.133    avatars2.githubusercontent.com
151.101.76.133    avatars3.githubusercontent.com
151.101.76.133    avatars4.githubusercontent.com
151.101.76.133    avatars5.githubusercontent.com
151.101.76.133    avatars6.githubusercontent.com
151.101.76.133    avatars7.githubusercontent.com
151.101.76.133    avatars8.githubusercontent.com
```
`npm cache clean -f`
ping raw.githubusercontent.com again

**Comment by fenglingnan** [comment]
> If ping raw.githubusercontent.com timed out
> add hosts
> 
> ```
> 52.74.223.119     github.com
> 192.30.253.119    gist.github.com
> 54.169.195.247    api.github.com
> 185.199.111.153   assets-cdn.github.com
> 151.101.76.133    raw.githubusercontent.com
> 151.101.76.133    gist.githubusercontent.com
> 151.101.76.133    cloud.githubusercontent.com
> 151.101.76.133    camo.githubusercontent.com
> 151.101.76.133    avatars0.githubusercontent.com
> 151.101.76.133    avatars1.githubusercontent.com
> 151.101.76.133    avatars2.githubusercontent.com
> 151.101.76.133    avatars3.githubusercontent.com
> 151.101.76.133    avatars4.githubusercontent.com
> 151.101.76.133    avatars5.githubusercontent.com
> 151.101.76.133    avatars6.githubusercontent.com
> 151.101.76.133    avatars7.githubusercontent.com
> 151.101.76.133    avatars8.githubusercontent.com
> ```
> 
> `npm cache clean -f`
> ping raw.githubusercontent.com again

greate！！
hours later  ,i saw you....
problem done...

**Comment by wanmaoor** [comment]
> If ping raw.githubusercontent.com timed out
> add hosts
> 
> ```
> 52.74.223.119     github.com
> 192.30.253.119    gist.github.com
> 54.169.195.247    api.github.com
> 185.199.111.153   assets-cdn.github.com
> 151.101.76.133    raw.githubusercontent.com
> 151.101.76.133    gist.githubusercontent.com
> 151.101.76.133    cloud.githubusercontent.com
> 151.101.76.133    camo.githubusercontent.com
> 151.101.76.133    avatars0.githubusercontent.com
> 151.101.76.133    avatars1.githubusercontent.com
> 151.101.76.133    avatars2.githubusercontent.com
> 151.101.76.133    avatars3.githubusercontent.com
> 151.101.76.133    avatars4.githubusercontent.com
> 151.101.76.133    avatars5.githubusercontent.com
> 151.101.76.133    avatars6.githubusercontent.com
> 151.101.76.133    avatars7.githubusercontent.com
> 151.101.76.133    avatars8.githubusercontent.com
> ```
> 
> `npm cache clean -f`
> ping raw.githubusercontent.com again

It works for me!

**Comment by Leslie-Wong-H** [comment]
This works for me. win10 
> npm install cnpm -g 
> cnpm install gifsicle -g

**Comment by DefectingCat** [comment]
> 
> 
> If ping raw.githubusercontent.com timed out
> add hosts
> 
> ```
> 52.74.223.119     github.com
> 192.30.253.119    gist.github.com
> 54.169.195.247    api.github.com
> 185.199.111.153   assets-cdn.github.com
> 151.101.76.133    raw.githubusercontent.com
> 151.101.76.133    gist.githubusercontent.com
> 151.101.76.133    cloud.githubusercontent.com
> 151.101.76.133    camo.githubusercontent.com
> 151.101.76.133    avatars0.githubusercontent.com
> 151.101.76.133    avatars1.githubusercontent.com
> 151.101.76.133    avatars2.githubusercontent.com
> 151.101.76.133    avatars3.githubusercontent.com
> 151.101.76.133    avatars4.githubusercontent.com
> 151.101.76.133    avatars5.githubusercontent.com
> 151.101.76.133    avatars6.githubusercontent.com
> 151.101.76.133    avatars7.githubusercontent.com
> 151.101.76.133    avatars8.githubusercontent.com
> ```
> 
> `npm cache clean -f`
> ping raw.githubusercontent.com again

thanks!
in the long time ,i think that it's my windows can not use the autoconf , though i installed cygwin

**Comment by XiayidanAlimu** [comment]
> 
> 
> You can try to use cnpm of Taobao mirror：
> 1、npm install -g cnpm --registry=https://registry.npm.taobao.org
> 2、cnpm i -g gifsicle

this one works for me, but only at the second attempt.
What a relief

**Comment by V2beach** [comment]
> 
> 
> You can try to use cnpm of Taobao mirror：
> 1、npm install -g cnpm --registry=https://registry.npm.taobao.org
> 2、cnpm i -g gifsicle

works for me, thx

**Comment by clabnet** [comment]
Not for me, on Windows 11, same issue.

```

D:\>npm install -g cnpm --registry=https://registry.npm.taobao.org
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

removed 384 packages, and changed 390 packages in 53s

D:\>cnpm i -g gifsicle
Downloading gifsicle to C:\Program Files\nodejs\node_modules\gifsicle_tmp
gifsicle@6.1.0 download from mirrors: {"https://raw.githubusercontent.com/imagemin/gifsicle-bin":"https://cdn.npmmirror.com/binaries/gifsicle-bin","https://raw.github.com/imagemin/gifsicle-bin":"https://cdn.npmmirror.com/binaries/gifsicle-bin"}, changed file: C:\Program Files\nodejs\node_modules\gifsicle_tmp\_gifsicle@6.1.0@gifsicle\lib\index.js
gifsicle@6.1.0 download from mirrors: {"https://raw.githubusercontent.com/imagemin/gifsicle-bin":"https://cdn.npmmirror.com/binaries/gifsicle-bin","https://raw.github.com/imagemin/gifsicle-bin":"https://cdn.npmmirror.com/binaries/gifsicle-bin"}, changed file: C:\Program Files\nodejs\node_modules\gifsicle_tmp\_gifsicle@6.1.0@gifsicle\lib\install.js
Copying C:\Program Files\nodejs\node_modules\gifsicle_tmp\_gifsicle@6.1.0@gifsicle to C:\Program Files\nodejs\node_modules\gifsicle
Installing gifsicle's dependencies to C:\Program Files\nodejs\node_modules\gifsicle/node_modules
[1/3] execa@^5.1.1 installed at node_modules\_execa@5.1.1@execa
[2/3] bin-build@^3.0.0 installed at node_modules\_bin-build@3.0.0@bin-build
[3/3] bin-wrapper@^4.0.0 installed at node_modules\_bin-wrapper@4.1.0@bin-wrapper
execute post install 1 scripts...
[1/1] scripts.postinstall gifsicle@6.1.0 run "node lib/install.js", root: "C:\\Program Files\\nodejs\\node_modules\\gifsicle"
Response code 404 (Not Found)
gifsicle pre-build test failed
compiling from source
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.


    at C:\ProgramData\nvm\v16.13.1\node_modules\gifsicle\node_modules\_execa@0.7.0@execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
[npminstall:runscript:error] gifsicle@6.1.0 scripts.postinstall run "node lib/install.js" error: Error [RunScriptError]: Run "C:\Windows\system32\cmd.exe /d /s /c node lib/install.js" error, exit code 1
    at ChildProcess.<anonymous> (C:\ProgramData\nvm\v16.13.1\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  stdio: [Object],
  exitcode: 1
}
Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node lib/install.js" error, exit code 1
RunScriptError: Run "C:\Windows\system32\cmd.exe /d /s /c node lib/install.js" error, exit code 1
    at ChildProcess.<anonymous> (C:\ProgramData\nvm\v16.13.1\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npminstall version: 5.4.0
npminstall args: C:\Program Files\nodejs\node.exe C:\ProgramData\nvm\v16.13.1\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\claud\.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com -g gifsicle

D:\>
```

**Comment by poindexterous** [comment]
I'm having the same issue on windows with a yarn package install involving gifsicle. However, I'm getting the same error if I use NPM
```
`[4/4] Building fresh packages...
[6/9] ⠁ pngquant-bin
[7/9] ⠁ node-sass
[3/9] ⠁ gifsicle
[8/9] ⠁ core-js
error C:\{project-path}\node_modules\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\{project-path}\node_modules\gifsicle
Output:
‼ self-signed certificate in certificate chain
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.`
```
This doesn't seem to have anything to do with raw.githubusercontent.com, I can ping that URL just fine with no timeout. This is something else. I stumbled across this thread in another forum, not sure if there's a relationship, but there might be something regarding the version of gifsicle-bin?
https://githubhot.com/repo/imagemin/gifsicle-bin/issues/133
https://github.com/imagemin/gifsicle-bin/releases/tag/v5.3.0
