### ISSUE TITLE
Failed at the gifsicle@4.0.1 postinstall script

### ISSUE THREAD

**Issue by danvoyce** [imagemin/imagemin-gifsicle#34]
I'm using imagemin in my Webpack build. It works well locally, but when I deploy it fails in my pipeline:

```
(node:52) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
  ⚠ Command failed: /root/project/node_modules/gifsicle/vendor/gifsicle --version
Error relocating /root/project/node_modules/gifsicle/vendor/gifsicle: __rawmemchr: symbol not found
```

Any ideas?

**Comment by maanishoo** [comment]
I have the same problem

**Comment by ankurmungekar** [comment]
i have same problem

```
> gifsicle@4.0.1 postinstall /app/node_modules/gifsicle
> node lib/install.js

  ⚠ spawn /app/node_modules/gifsicle/vendor/gifsicle ENOENT
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: not found


    at /app/node_modules/bin-build/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

**Comment by 1000ch** [comment]
Please try the newest version and install `autoreconf` or prepare the dependencies related to [gifsicle](https://github.com/kohler/gifsicle).

**Comment by G-WangZH** [comment]
I have the same problem

**Comment by taragurung** [comment]
same issue
