### ISSUE TITLE
NPM failure

### ISSUE THREAD

**Issue by djforth** [imagemin/imagemin-gifsicle#6]
getting the following error when I try to install, any ideas on what might be coursing it?:

```
gifsicle@3.0.1 postinstall /Users/djforth/websites/gll_generic/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/djforth/websites/gll_generic/node_modules/glob/glob.js:46:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by djforth** [comment]
Re-reading the output I realised it was something to do with glob.js. As I wasn't actually using it anywhere else I killed and now seems to install fine.
